import os

configfile: "../config/config.yaml"

######## Load rules ########
include: "rules/minimap2.smk"
include: "rules/stringtie.smk"
include: "rules/gtf_processing.smk"
include: "rules/annotation.smk"

##### Setup Singularity #####
# with --use-singularity
container: "docker://aucam/lorid:latest"

######## Target rule ########
rule all:
  input:
    f"{config['dirs']['outdir']}/SOSTAR_annotation_table_results.xlsx"